apiVersion: apps/v1
kind: Deployment
metadata: 
name: demo-deployment
labels:
 app: demo-app
spec: 
replicas: 1
selector:
 matchLabels:
  app: demo-app
template: 
  metadata: 
   labels: 
    app: demo-app
  spec: 
    containers: 
    - name: demo-app
      image: pranav27\devops-image:tagVersion
      command: ["/bin/sh"]
        args: ["-c","sh /usr/local/tomcat/bin/startup.sh;while true; do echo hello; sleep 10;done"]
      ports:
      - containerPort: 8080
