apiVersion: v1
kind: Pod
metadata:
  name: demoapp
  labels:
    app: demoapp
spec:
  containers:
    - name: demoapp
      image: pranav27/devops-image:tagVersion
      ports:
       -  name: demoapp
          containerPort: 80
