apiVersion: apps/v1
kind: Service
metadata: 
 name: demoapp
 labels:
   app: demoapp
spec: 
  selector:
    app: demoapp
  ports:
   -protocol: TCP
     port: 80
    targetPort: 8080
  type: LoadBalancer
